### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by alexandru-dinu** [alexandru-dinu/ir-project#1]
**Android**
- [x] add OpenCV lib
- [x] run on phone
- [x] get Camera View
- [x] get and process current frame
- [x] draw
- [ ] full screen
- [ ] landscape
- [ ] **put intensive work on separate thread**
    - [ref-1](https://stackoverflow.com/questions/15799487/parallel-image-detection-and-camera-preview-opencv-android)
    - [ref-2](http://ibuzzlog.blogspot.com/2012/08/how-to-do-real-time-image-processing-in.html)
    - [AsyncTask](https://developer.android.com/reference/android/os/AsyncTask.html)

---

**CV**
- [x] use HSV / HSL / grayscale thresholding (apart from RGB)
- [ ] exponential decay over frames
- [x] ROI + thresholding by theta returned by `HoughLines` 
- [x] something other than Hough?
- [x] noise removal
- [x] **segmentation**
